import type { DMMF } from "@prisma/generator-helper";
import { describe, expect, it } from "vitest";
import type { GeneratorConfig } from "./config.js";
import { generate } from "./generate.js";

// ============================================================================
// Test Fixtures
// ============================================================================

const defaultConfig: GeneratorConfig = {
  includeRelations: false,
  useBrandedIds: true,
  dateTimeHandling: "Date",
  sortFields: true,
  customHeader: null,
};

const makeField = (overrides: Partial<DMMF.Field>): DMMF.Field =>
  ({
    name: "testField",
    kind: "scalar",
    isList: false,
    isRequired: true,
    isUnique: false,
    isId: false,
    isReadOnly: false,
    isGenerated: false,
    isUpdatedAt: false,
    type: "String",
    hasDefaultValue: false,
    ...overrides,
  }) as DMMF.Field;

const makeRelationField = (
  name: string,
  type: string,
  relationFromFields: string[],
  isList = false
): DMMF.Field =>
  makeField({
    name,
    kind: "object",
    type,
    isList,
    relationFromFields,
    relationToFields: ["id"],
  });

const makeModel = (
  name: string,
  fields: Partial<DMMF.Field>[]
): DMMF.Model =>
  ({
    name,
    fields: fields.map((f) => makeField({ ...f })),
    primaryKey: null,
    uniqueFields: [],
    uniqueIndexes: [],
    dbName: null,
    schema: null,
    isGenerated: false,
  }) as DMMF.Model;

const makeModelWithRelations = (
  name: string,
  scalarFields: Partial<DMMF.Field>[],
  relationFields: Array<{ name: string; type: string; fkFields: string[]; isList?: boolean }>
): DMMF.Model => {
  const scalars = scalarFields.map((f) => makeField({ ...f }));
  const relations = relationFields.map((r) =>
    makeRelationField(r.name, r.type, r.fkFields, r.isList)
  );
  return {
    name,
    fields: [...scalars, ...relations],
    primaryKey: null,
    uniqueFields: [],
    uniqueIndexes: [],
    dbName: null,
    schema: null,
    isGenerated: false,
  } as DMMF.Model;
};

const makeEnum = (
  name: string,
  values: string[]
): DMMF.DatamodelEnum =>
  ({
    name,
    values: values.map((v) => ({ name: v, dbName: null })),
    dbName: null,
  }) as DMMF.DatamodelEnum;

const makeDmmf = (
  models: DMMF.Model[],
  enums: DMMF.DatamodelEnum[] = []
): DMMF.Document =>
  ({
    datamodel: { models, enums },
  }) as unknown as DMMF.Document;

// ============================================================================
// Basic Model Generation
// ============================================================================

describe("generate", () => {
  describe("basic model with scalar fields", () => {
    it("generates schema for model with various scalar types", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "email", type: "String" },
          { name: "age", type: "Int" },
          { name: "balance", type: "Float" },
          { name: "active", type: "Boolean" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toMatchInlineSnapshot(`
        "// This file was auto-generated by prisma-effect-schema
        // Do not edit manually - changes will be overwritten
        // https://github.com/frontcore/prisma-effect-schema

        import { Schema } from "effect"// ============================================================================
        // Branded IDs
        // ============================================================================export const UserId = Schema.String.pipe(Schema.brand("UserId"))
        export type UserId = typeof UserId.Type// ============================================================================
        // Models (scalar fields only)
        // ============================================================================export const User = Schema.Struct({
              active: Schema.Boolean,
        age: Schema.Int,
        balance: Schema.Number,
        email: Schema.String,
        id: UserId
          })
          export type User = typeof User.Type"
      `);
      expect(result.stats).toEqual({
        enumCount: 0,
        modelCount: 1,
        brandedIdCount: 1,
      });
    });
  });

  // ============================================================================
  // Branded IDs
  // ============================================================================

  describe("branded IDs", () => {
    it("generates branded ID for String @id field", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "title", type: "String" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain('export const PostId = Schema.String.pipe(Schema.brand("PostId"))');
      expect(result.content).toContain("id: PostId");
      expect(result.stats.brandedIdCount).toBe(1);
    });

    it("uses slug suffix for slug-based primary keys", () => {
      const models = [
        makeModel("Course", [
          { name: "slug", type: "String", isId: true },
          { name: "title", type: "String" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain('export const CourseSlug = Schema.String.pipe(Schema.brand("CourseSlug"))');
      expect(result.content).toContain("slug: CourseSlug");
    });

    it("skips branded IDs for Int primary keys", () => {
      const models = [
        makeModel("Counter", [
          { name: "id", type: "Int", isId: true },
          { name: "value", type: "Int" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).not.toContain("CounterId");
      expect(result.content).not.toContain("Branded IDs");
      expect(result.stats.brandedIdCount).toBe(0);
    });

    it("respects useBrandedIds=false config", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "email", type: "String" },
        ]),
      ];
      const config = { ...defaultConfig, useBrandedIds: false };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).not.toContain("UserId");
      expect(result.content).not.toContain("Branded IDs");
      expect(result.content).toContain("id: Schema.String");
    });
  });

  // ============================================================================
  // Foreign Keys
  // ============================================================================

  describe("foreign key resolution", () => {
    it("resolves FK to target model branded ID", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
        makeModelWithRelations(
          "Post",
          [
            { name: "id", type: "String", isId: true },
            { name: "authorId", type: "String" },
            { name: "title", type: "String" },
          ],
          [{ name: "author", type: "User", fkFields: ["authorId"] }]
        ),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toMatchInlineSnapshot(`
        "// This file was auto-generated by prisma-effect-schema
        // Do not edit manually - changes will be overwritten
        // https://github.com/frontcore/prisma-effect-schema

        import { Schema } from "effect"// ============================================================================
        // Branded IDs
        // ============================================================================export const PostId = Schema.String.pipe(Schema.brand("PostId"))
        export type PostId = typeof PostId.Type

        export const UserId = Schema.String.pipe(Schema.brand("UserId"))
        export type UserId = typeof UserId.Type// ============================================================================
        // Models (scalar fields only)
        // ============================================================================export const Post = Schema.Struct({
              authorId: UserId,
        id: PostId,
        title: Schema.String
          })
          export type Post = typeof Post.Type
        export const User = Schema.Struct({
            id: UserId
        })
        export type User = typeof User.Type"
      `);
    });

    it("resolves non-standard FK names using relation metadata", () => {
      const models = [
        makeModel("File", [{ name: "id", type: "String", isId: true }]),
        makeModelWithRelations(
          "User",
          [
            { name: "id", type: "String", isId: true },
            { name: "avatarId", type: "String", isRequired: false },
          ],
          [{ name: "avatarFile", type: "File", fkFields: ["avatarId"] }]
        ),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      // avatarId resolves to FileId (not UserId)
      expect(result.content).toContain("avatarId: Schema.NullOr(FileId)");
    });
  });

  // ============================================================================
  // Enums
  // ============================================================================

  describe("enums", () => {
    it("generates enum schema with sorted values", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "status", kind: "enum", type: "PostStatus" },
        ]),
      ];
      const enums = [makeEnum("PostStatus", ["PUBLISHED", "DRAFT", "ARCHIVED"])];

      const result = generate({ dmmf: makeDmmf(models, enums), config: defaultConfig });

      expect(result.content).toMatchInlineSnapshot(`
        "// This file was auto-generated by prisma-effect-schema
        // Do not edit manually - changes will be overwritten
        // https://github.com/frontcore/prisma-effect-schema

        import { Schema } from "effect"// ============================================================================
        // Enums
        // ============================================================================export const PostStatus = Schema.Literal("ARCHIVED", "DRAFT", "PUBLISHED")
        export type PostStatus = typeof PostStatus.Type// ============================================================================
        // Branded IDs
        // ============================================================================export const PostId = Schema.String.pipe(Schema.brand("PostId"))
        export type PostId = typeof PostId.Type// ============================================================================
        // Models (scalar fields only)
        // ============================================================================export const Post = Schema.Struct({
              id: PostId,
        status: PostStatus
          })
          export type Post = typeof Post.Type"
      `);
      expect(result.stats.enumCount).toBe(1);
    });

    it("generates multiple enums sorted by name", () => {
      const models: DMMF.Model[] = [];
      const enums = [
        makeEnum("Role", ["ADMIN", "USER"]),
        makeEnum("Status", ["ACTIVE", "INACTIVE"]),
      ];

      const result = generate({ dmmf: makeDmmf(models, enums), config: defaultConfig });

      expect(result.content).toContain("export const Role = Schema.Literal");
      expect(result.content).toContain("export const Status = Schema.Literal");
      // Role should come before Status (alphabetical)
      expect(result.content.indexOf("Role")).toBeLessThan(result.content.indexOf("Status"));
    });
  });

  // ============================================================================
  // JSON Fields
  // ============================================================================

  describe("JSON fields", () => {
    it("includes JsonValueSchema when model has Json field", () => {
      const models = [
        makeModel("Settings", [
          { name: "id", type: "String", isId: true },
          { name: "data", type: "Json" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("type JsonValue = string | number | boolean | null | JsonArray | JsonObject");
      expect(result.content).toContain("const JsonValueSchema: Schema.Schema<JsonValue>");
      expect(result.content).toContain("data: JsonValueSchema");
    });

    it("omits JsonValueSchema when no Json fields exist", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "name", type: "String" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).not.toContain("JsonValue");
      expect(result.content).not.toContain("JsonValueSchema");
    });
  });

  // ============================================================================
  // DateTime Handling
  // ============================================================================

  describe("DateTime handling", () => {
    it("uses Schema.Date with dateTimeHandling=Date (default)", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "createdAt", type: "DateTime" },
        ]),
      ];
      const config = { ...defaultConfig, dateTimeHandling: "Date" as const };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).toContain("createdAt: Schema.Date");
    });

    it("uses Schema.DateTimeUtc with dateTimeHandling=DateTimeString", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "createdAt", type: "DateTime" },
        ]),
      ];
      const config = { ...defaultConfig, dateTimeHandling: "DateTimeString" as const };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).toContain("createdAt: Schema.DateTimeUtc");
    });
  });

  // ============================================================================
  // Relations (includeRelations config)
  // ============================================================================

  describe("relations", () => {
    it("excludes relation fields by default", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
        makeModelWithRelations(
          "Post",
          [
            { name: "id", type: "String", isId: true },
            { name: "authorId", type: "String" },
          ],
          [{ name: "author", type: "User", fkFields: ["authorId"] }]
        ),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).not.toContain("author: Schema.suspend");
      expect(result.content).not.toContain("PostWithRelations");
    });

    it("generates WithRelations schema when includeRelations=true", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
        makeModelWithRelations(
          "Post",
          [
            { name: "id", type: "String", isId: true },
            { name: "authorId", type: "String" },
            { name: "title", type: "String" },
          ],
          [{ name: "author", type: "User", fkFields: ["authorId"] }]
        ),
      ];
      const config = { ...defaultConfig, includeRelations: true };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).toContain("export const Post = Schema.Struct");
      expect(result.content).toContain("export const PostWithRelations = Schema.Struct");
      expect(result.content).toContain("author: Schema.suspend(() => User)");
    });

    it("handles list relations with Array wrapper", () => {
      const models = [
        makeModelWithRelations(
          "User",
          [{ name: "id", type: "String", isId: true }],
          [{ name: "posts", type: "Post", fkFields: [], isList: true }]
        ),
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "authorId", type: "String" },
        ]),
      ];
      const config = { ...defaultConfig, includeRelations: true };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).toContain("posts: Schema.Array(Schema.suspend(() => Post))");
    });
  });

  // ============================================================================
  // Field Wrappers (optional, list)
  // ============================================================================

  describe("field wrappers", () => {
    it("wraps optional fields with Schema.NullOr", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "bio", type: "String", isRequired: false },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("bio: Schema.NullOr(Schema.String)");
    });

    it("wraps list fields with Schema.Array", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "tags", type: "String", isList: true },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("tags: Schema.Array(Schema.String)");
    });

    it("wraps optional list fields with both wrappers", () => {
      const models = [
        makeModel("Post", [
          { name: "id", type: "String", isId: true },
          { name: "tags", type: "String", isList: true, isRequired: false },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("tags: Schema.NullOr(Schema.Array(Schema.String))");
    });
  });

  // ============================================================================
  // Sorting
  // ============================================================================

  describe("sorting", () => {
    it("sorts fields alphabetically when sortFields=true", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "zebra", type: "String" },
          { name: "alpha", type: "String" },
        ]),
      ];
      const config = { ...defaultConfig, sortFields: true };

      const result = generate({ dmmf: makeDmmf(models), config });

      const alphaIndex = result.content.indexOf("alpha:");
      const idIndex = result.content.indexOf("id:");
      const zebraIndex = result.content.indexOf("zebra:");

      expect(alphaIndex).toBeLessThan(idIndex);
      expect(idIndex).toBeLessThan(zebraIndex);
    });

    it("preserves field order when sortFields=false", () => {
      const models = [
        makeModel("User", [
          { name: "id", type: "String", isId: true },
          { name: "zebra", type: "String" },
          { name: "alpha", type: "String" },
        ]),
      ];
      const config = { ...defaultConfig, sortFields: false };

      const result = generate({ dmmf: makeDmmf(models), config });

      const idIndex = result.content.indexOf("id:");
      const zebraIndex = result.content.indexOf("zebra:");
      const alphaIndex = result.content.indexOf("alpha:");

      expect(idIndex).toBeLessThan(zebraIndex);
      expect(zebraIndex).toBeLessThan(alphaIndex);
    });

    it("sorts models alphabetically", () => {
      const models = [
        makeModel("Zebra", [{ name: "id", type: "String", isId: true }]),
        makeModel("Alpha", [{ name: "id", type: "String", isId: true }]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content.indexOf("export const Alpha")).toBeLessThan(
        result.content.indexOf("export const Zebra")
      );
    });
  });

  // ============================================================================
  // Custom Header
  // ============================================================================

  describe("custom header", () => {
    it("uses default header when customHeader is null", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("// This file was auto-generated by prisma-effect-schema");
      expect(result.content).toContain('import { Schema } from "effect"');
    });

    it("uses custom header when provided", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
      ];
      const config = {
        ...defaultConfig,
        customHeader: `// Custom header\nimport { Schema } from "effect"`,
      };

      const result = generate({ dmmf: makeDmmf(models), config });

      expect(result.content).toContain("// Custom header");
      expect(result.content).not.toContain("// This file was auto-generated");
    });
  });

  // ============================================================================
  // Edge Cases
  // ============================================================================

  describe("edge cases", () => {
    it("handles empty models array", () => {
      const result = generate({ dmmf: makeDmmf([]), config: defaultConfig });

      expect(result.stats).toEqual({
        enumCount: 0,
        modelCount: 0,
        brandedIdCount: 0,
      });
      expect(result.content).toContain("// Models (scalar fields only)");
    });

    it("handles model with only primary key", () => {
      const models = [
        makeModel("Token", [{ name: "id", type: "String", isId: true }]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toMatchInlineSnapshot(`
        "// This file was auto-generated by prisma-effect-schema
        // Do not edit manually - changes will be overwritten
        // https://github.com/frontcore/prisma-effect-schema

        import { Schema } from "effect"// ============================================================================
        // Branded IDs
        // ============================================================================export const TokenId = Schema.String.pipe(Schema.brand("TokenId"))
        export type TokenId = typeof TokenId.Type// ============================================================================
        // Models (scalar fields only)
        // ============================================================================export const Token = Schema.Struct({
            id: TokenId
        })
        export type Token = typeof Token.Type"
      `);
    });

    it("handles multiple FKs to same model", () => {
      const models = [
        makeModel("User", [{ name: "id", type: "String", isId: true }]),
        makeModelWithRelations(
          "Transfer",
          [
            { name: "id", type: "String", isId: true },
            { name: "fromUserId", type: "String" },
            { name: "toUserId", type: "String" },
          ],
          [
            { name: "fromUser", type: "User", fkFields: ["fromUserId"] },
            { name: "toUser", type: "User", fkFields: ["toUserId"] },
          ]
        ),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("fromUserId: UserId");
      expect(result.content).toContain("toUserId: UserId");
    });

    it("handles all Prisma scalar types", () => {
      const models = [
        makeModel("AllTypes", [
          { name: "id", type: "String", isId: true },
          { name: "int", type: "Int" },
          { name: "float", type: "Float" },
          { name: "bool", type: "Boolean" },
          { name: "str", type: "String" },
          { name: "date", type: "DateTime" },
          { name: "bigint", type: "BigInt" },
          { name: "decimal", type: "Decimal" },
          { name: "bytes", type: "Bytes" },
          { name: "json", type: "Json" },
        ]),
      ];

      const result = generate({ dmmf: makeDmmf(models), config: defaultConfig });

      expect(result.content).toContain("int: Schema.Int");
      expect(result.content).toContain("float: Schema.Number");
      expect(result.content).toContain("bool: Schema.Boolean");
      expect(result.content).toContain("str: Schema.String");
      expect(result.content).toContain("date: Schema.Date");
      expect(result.content).toContain("bigint: Schema.BigInt");
      expect(result.content).toContain("decimal: Schema.Decimal");
      expect(result.content).toContain("bytes: Schema.Uint8Array");
      expect(result.content).toContain("json: JsonValueSchema");
    });
  });
});
