import type { DMMF } from "@prisma/generator-helper";
import dedent from "dedent";
import { Array as Arr, HashMap, Option, Order, pipe, Record } from "effect";
import { capitalize } from "effect/String";
import type { GeneratorConfig } from "./config.js";
import { UnsupportedTypeError } from "./errors.js";
import { removeIdSuffix } from "./utils.js";

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_HEADER = dedent`
  // This file was auto-generated by prisma-effect-schema
  // Do not edit manually - changes will be overwritten
  // https://github.com/frontcore/prisma-effect-schema

  import { Schema } from "effect"
`;

const JSON_VALUE_SCHEMA = dedent`

  // Recursive JSON value schema matching Prisma's JsonValue type
  type JsonValue = string | number | boolean | null | JsonArray | JsonObject
  type JsonArray = ReadonlyArray<JsonValue>
  type JsonObject = { readonly [key: string]: JsonValue }

  const JsonValueSchema: Schema.Schema<JsonValue> = Schema.suspend(
    (): Schema.Schema<JsonValue> =>
      Schema.Union(
        Schema.Null,
        Schema.Boolean,
        Schema.Number,
        Schema.String,
        Schema.Array(JsonValueSchema),
        Schema.Record({ key: Schema.String, value: JsonValueSchema })
      )
  )
`;

/** Simple scalar type mappings (non-String types) */
const ScalarTypeMap: Record.ReadonlyRecord<string, string> = {
  Int: "Schema.Int",
  Float: "Schema.Number",
  Boolean: "Schema.Boolean",
  DateTime: "Schema.Date",
  Json: "JsonValueSchema",
  Bytes: "Schema.Uint8Array",
  BigInt: "Schema.BigInt",
  Decimal: "Schema.String",
};

// ============================================================================
// Helpers
// ============================================================================

const sectionHeader = (title: string): string => dedent`
  // ============================================================================
  // ${title}
  // ============================================================================

`;

const ByName = <T extends { name: string }>(): Order.Order<T> =>
  Order.mapInput(Order.string, (item: T) => item.name);

const sortByName = <T extends { name: string }>(items: readonly T[]): T[] =>
  Arr.sort(items, ByName());

export const makeUnsupportedTypeError = (
  typeName: string,
  fieldName: string,
  modelName: string,
): UnsupportedTypeError =>
  new UnsupportedTypeError({
    typeName,
    fieldName,
    modelName,
  });

// ============================================================================
// Branded ID Collection
// ============================================================================

/**
 * Collects branded IDs for models with string primary keys.
 * Returns a HashMap of modelName -> brandedIdName (e.g., "User" -> "UserId")
 */
const collectBrandedIds = (
  models: readonly DMMF.Model[],
): HashMap.HashMap<string, string> =>
  pipe(
    models,
    Arr.filter((model) =>
      model.fields.some((f) => f.isId && f.type === "String"),
    ),
    Arr.map((model) => [model.name, `${model.name}Id`] as const),
    HashMap.fromIterable,
  );

// ============================================================================
// Field Type Resolution
// ============================================================================

interface FieldContext {
  field: DMMF.Field;
  modelName: string;
  brandedIds: HashMap.HashMap<string, string>;
  config: GeneratorConfig;
}

/**
 * Resolves the branded ID for a String field if applicable.
 * - Primary keys get their model's branded ID
 * - Foreign keys (ending in "Id") get the referenced model's branded ID
 */
const resolveBrandedId = (ctx: FieldContext): Option.Option<string> => {
  const { field, modelName, brandedIds, config } = ctx;

  if (!config.useBrandedIds) return Option.none();

  // Primary key uses this model's branded ID
  if (field.isId) {
    return HashMap.get(brandedIds, modelName);
  }

  // Foreign key - strip "Id" suffix and look up the referenced model
  const baseName = removeIdSuffix(field.name);
  if (baseName === field.name) return Option.none(); // No suffix was removed

  return pipe(baseName, capitalize, (refModel) =>
    HashMap.get(brandedIds, refModel),
  );
};

/**
 * Maps a Prisma scalar type to an Effect Schema expression.
 */
const resolveScalarType = (ctx: FieldContext): string => {
  const { field, modelName } = ctx;

  // Check non-String scalar types first
  const simpleMapping = Record.get(ScalarTypeMap, field.type);
  if (Option.isSome(simpleMapping)) {
    return simpleMapping.value;
  }

  // String type: try branded ID, fallback to Schema.String
  if (field.type === "String") {
    return pipe(
      resolveBrandedId(ctx),
      Option.getOrElse(() => "Schema.String"),
    );
  }

  throw makeUnsupportedTypeError(field.type, field.name, modelName);
};

/**
 * Resolves the base schema type for a field (before list/optional wrappers).
 */
const resolveBaseType = (ctx: FieldContext): string => {
  const { kind, type } = ctx.field;

  switch (kind) {
    case "enum":
      return type;
    case "object":
      return `Schema.suspend(() => ${type})`;
    default:
      return resolveScalarType(ctx);
  }
};

/**
 * Wraps a schema type with Array if the field is a list.
 */
const wrapIfList = (schemaType: string, isList: boolean): string =>
  isList ? `Schema.Array(${schemaType})` : schemaType;

/**
 * Wraps a schema type with NullOr if the field is optional.
 * In Prisma, optional fields can be null in DB and are returned as null.
 */
const wrapIfOptional = (schemaType: string, isRequired: boolean): string =>
  isRequired ? schemaType : `Schema.NullOr(${schemaType})`;

/**
 * Maps a Prisma field to its complete Effect Schema expression.
 */
const mapFieldToSchema = (ctx: FieldContext): string =>
  pipe(
    resolveBaseType(ctx),
    (base) => wrapIfList(base, ctx.field.isList),
    (wrapped) => wrapIfOptional(wrapped, ctx.field.isRequired),
  );

// ============================================================================
// Code Generation
// ============================================================================

const generateEnumSchema = (enumDef: DMMF.DatamodelEnum): string => {
  const values = pipe(
    sortByName(enumDef.values),
    Arr.map((v) => `"${v.name}"`),
    Arr.join(", "),
  );

  return dedent`
    export const ${enumDef.name} = Schema.Literal(${values})
    export type ${enumDef.name} = typeof ${enumDef.name}.Type
  `;
};

const generateBrandedIdSchema = ([, brandedIdName]: readonly [
  string,
  string,
]): string =>
  dedent`
    export const ${brandedIdName} = Schema.String.pipe(Schema.brand("${brandedIdName}"))
    export type ${brandedIdName} = typeof ${brandedIdName}.Type
  `;

const generateBrandedIdSchemas = (
  brandedIds: HashMap.HashMap<string, string>,
): string =>
  pipe(
    brandedIds,
    HashMap.toEntries,
    Arr.sort(Order.mapInput(Order.string, ([key]: [string, string]) => key)),
    Arr.map(generateBrandedIdSchema),
    Arr.join("\n\n"),
  );

const generateFieldsCode = (
  fields: readonly DMMF.Field[],
  modelName: string,
  brandedIds: HashMap.HashMap<string, string>,
  config: GeneratorConfig,
): string =>
  pipe(
    config.sortFields ? sortByName(fields) : fields,
    Arr.map((field) => {
      const ctx: FieldContext = { field, modelName, brandedIds, config };
      return `  ${field.name}: ${mapFieldToSchema(ctx)}`;
    }),
    Arr.join(",\n"),
  );

const generateModelSchema = (
  model: DMMF.Model,
  brandedIds: HashMap.HashMap<string, string>,
  config: GeneratorConfig,
): string => {
  const scalarFields = model.fields.filter((f) => f.kind !== "object");
  const hasRelations = model.fields.some((f) => f.kind === "object");

  const scalarFieldsCode = generateFieldsCode(
    scalarFields,
    model.name,
    brandedIds,
    config,
  );

  const baseSchema = dedent`
    export const ${model.name} = Schema.Struct({
      ${scalarFieldsCode}
    })
    export type ${model.name} = typeof ${model.name}.Type
  `;

  // Optionally generate schema with relations
  if (!config.includeRelations || !hasRelations) {
    return baseSchema;
  }

  const allFieldsCode = generateFieldsCode(
    model.fields,
    model.name,
    brandedIds,
    config,
  );

  return dedent`
    ${baseSchema}

    export const ${model.name}WithRelations = Schema.Struct({
      ${allFieldsCode}
    })
    export type ${model.name}WithRelations = typeof   ${model.name}WithRelations.Type
  `;
};

// ============================================================================
// Main Entry Point
// ============================================================================

export interface GenerateInput {
  dmmf: DMMF.Document;
  config: GeneratorConfig;
}

export interface GenerateOutput {
  content: string;
  stats: {
    enumCount: number;
    modelCount: number;
    brandedIdCount: number;
  };
}

/**
 * Generates Effect Schema source code from Prisma DMMF.
 */
export const generate = (input: GenerateInput): GenerateOutput => {
  const { dmmf, config } = input;
  const { models, enums } = dmmf.datamodel;

  const brandedIds = config.useBrandedIds
    ? collectBrandedIds(models)
    : HashMap.empty<string, string>();

  const brandedIdCount = HashMap.size(brandedIds);

  const sections = [
    // Header
    config.customHeader ?? DEFAULT_HEADER,
    // JSON schema (always needed for Json fields)
    JSON_VALUE_SCHEMA,
    // Enums
    ...(enums.length > 0
      ? [
          sectionHeader("Enums"),
          pipe(sortByName(enums), Arr.map(generateEnumSchema), Arr.join("\n")),
        ]
      : []),
    // Branded IDs
    ...(brandedIdCount > 0
      ? [sectionHeader("Branded IDs"), generateBrandedIdSchemas(brandedIds), ""]
      : []),
    // Models
    sectionHeader("Models (scalar fields only)"),
    pipe(
      sortByName(models),
      Arr.map((model) => generateModelSchema(model, brandedIds, config)),
      Arr.join("\n"),
    ),
  ];

  return {
    content: sections.join(""),
    stats: {
      enumCount: enums.length,
      modelCount: models.length,
      brandedIdCount,
    },
  };
};
