/**
 * Core generation logic for Effect Schemas from Prisma DMMF
 */
import type { DMMF } from "@prisma/generator-helper";
import dedent from "dedent";
import { Schema } from "effect";
import { capitalize } from "effect/String";
import type { ResolvedConfig } from "./types.js";
import { removeIdSuffix } from "./utils.js";

// Static header without timestamps to avoid git churn
const DEFAULT_HEADER = dedent`
  // This file was auto-generated by prisma-effect-schema
  // Do not edit manually - changes will be overwritten
  // https://github.com/frontcore/prisma-effect-schema

  import { Schema } from "effect"
`;

// JSON value schema that properly handles Prisma's JsonValue type
// Uses Schema.suspend for the recursive definition
const JSON_VALUE_SCHEMA = dedent`

  // Recursive JSON value schema matching Prisma's JsonValue type
  type JsonValue = string | number | boolean | null | JsonArray | JsonObject
  type JsonArray = ReadonlyArray<JsonValue>
  type JsonObject = { readonly [key: string]: JsonValue }

  const JsonValueSchema: Schema.Schema<JsonValue> = Schema.suspend(
    (): Schema.Schema<JsonValue> =>
      Schema.Union(
        Schema.Null,
        Schema.Boolean,
        Schema.Number,
        Schema.String,
        Schema.Array(JsonValueSchema),
        Schema.Record({ key: Schema.String, value: JsonValueSchema })
      )
  )
`;

function sectionHeader(title: string): string {
  return `
// ============================================================================
// ${title}
// ============================================================================

`;
}

/**
 * Error thrown when an unsupported Prisma type is encountered
 */
export class UnsupportedTypeError extends Schema.TaggedError<UnsupportedTypeError>()(
  "UnsupportedTypeError",
  {
    typeName: Schema.String,
    fieldName: Schema.String,
    modelName: Schema.String,
    message: Schema.String,
  },
) {}

/**
 * Create an UnsupportedTypeError with a formatted message
 */
export function makeUnsupportedTypeError(
  typeName: string,
  fieldName: string,
  modelName: string,
): UnsupportedTypeError {
  return new UnsupportedTypeError({
    typeName,
    fieldName,
    modelName,
    message:
      `Unsupported Prisma type "${typeName}" for field "${fieldName}" in model "${modelName}". ` +
      `Please open an issue at https://github.com/frontcore/prisma-effect-schema/issues`,
  });
}

interface FieldContext {
  field: DMMF.Field;
  modelName: string;
  brandedIds: Map<string, string>; // modelName -> brandedIdName
  config: ResolvedConfig;
}

/**
 * Maps a Prisma scalar type to an Effect Schema expression
 */
function mapScalarType(ctx: FieldContext): string {
  const { field, modelName, brandedIds, config } = ctx;
  const { type } = field;

  switch (type) {
    case "String":
      // Check if this is an ID field that should use a branded type
      if (field.isId && config.useBrandedIds) {
        const brandedId = brandedIds.get(modelName);
        if (brandedId) {
          return brandedId;
        }
      }
      // Check if this is a foreign key referencing another model's ID
      if (config.useBrandedIds && removeIdSuffix(field.name) && !field.isId) {
        // Try to find the referenced model's branded ID
        const refModelName = removeIdSuffix(field.name);
        // Capitalize first letter
        const capitalizedRefModel = capitalize(refModelName);
        const refBrandedId = brandedIds.get(capitalizedRefModel);
        if (refBrandedId) {
          return refBrandedId;
        }
      }
      return "Schema.String";

    case "Int":
      return "Schema.Int";

    case "Float":
      return "Schema.Number";

    case "Boolean":
      return "Schema.Boolean";

    case "DateTime":
      // Schema.Date validates Date objects (what Prisma returns)
      // For API validation where dates come as strings, users should
      // compose with Schema.parseDate or use DateTimeString mode
      return "Schema.Date";

    case "Json":
      return "JsonValueSchema";

    case "Bytes":
      return "Schema.Uint8Array";

    case "BigInt":
      return "Schema.BigInt";

    case "Decimal":
      // Prisma returns Decimal as Prisma.Decimal in JS, which serializes to string
      // Using Schema.String is the safest choice for interop
      return "Schema.String";

    default:
      throw makeUnsupportedTypeError(type, field.name, modelName);
  }
}

/**
 * Maps a Prisma field to an Effect Schema expression
 */
function mapFieldToSchema(ctx: FieldContext): string {
  const { field, modelName, brandedIds, config } = ctx;
  const { kind, type, isRequired, isList } = field;

  let schemaType: string;

  if (kind === "enum") {
    // Reference the generated enum schema
    schemaType = type;
  } else if (kind === "object") {
    // Relation field - use lazy reference to handle circular dependencies
    schemaType = `Schema.suspend(() => ${type})`;
  } else {
    // Scalar types
    schemaType = mapScalarType(ctx);
  }

  // Handle arrays first
  if (isList) {
    schemaType = `Schema.Array(${schemaType})`;
  }

  // Handle optionality/nullability
  // In Prisma:
  // - Required field (no ?): always present, never null
  // - Optional field (?): can be null in DB, returned as null from Prisma
  // For read models (what Prisma returns), we use Schema.NullOr
  // The field is always present in the object, but its value can be null
  if (!isRequired) {
    schemaType = `Schema.NullOr(${schemaType})`;
  }

  return schemaType;
}

/**
 * Generates Effect Schema code for a Prisma enum
 */
function generateEnumSchema(enumDef: DMMF.DatamodelEnum): string {
  const sortedValues = [...enumDef.values].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  const values = sortedValues.map((v) => `"${v.name}"`).join(", ");

  return `export const ${enumDef.name} = Schema.Literal(${values})
export type ${enumDef.name} = typeof ${enumDef.name}.Type
`;
}

/**
 * Generates branded ID types for models with string IDs
 * Returns a map of modelName -> brandedIdName for use in model generation
 */
function collectBrandedIds(models: readonly DMMF.Model[]): Map<string, string> {
  const brandedIds = new Map<string, string>();

  for (const model of models) {
    const idField = model.fields.find((f) => f.isId);
    if (idField && idField.type === "String") {
      brandedIds.set(model.name, `${model.name}Id`);
    }
  }

  return brandedIds;
}

/**
 * Generates branded ID schema definitions
 */
function generateBrandedIdSchemas(brandedIds: Map<string, string>): string {
  if (brandedIds.size === 0) return "";

  const sortedEntries = [...brandedIds.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  );

  const schemas = sortedEntries
    .map(
      ([, brandedIdName]) =>
        `export const ${brandedIdName} = Schema.String.pipe(Schema.brand("${brandedIdName}"))
export type ${brandedIdName} = typeof ${brandedIdName}.Type`,
    )
    .join("\n\n");

  return schemas;
}

/**
 * Generates Effect Schema code for a Prisma model
 */
function generateModelSchema(
  model: DMMF.Model,
  brandedIds: Map<string, string>,
  config: ResolvedConfig,
): string {
  const scalarFields = model.fields.filter((f) => f.kind !== "object");
  const relationFields = model.fields.filter((f) => f.kind === "object");

  // Sort fields if configured
  const sortedScalarFields = config.sortFields
    ? [...scalarFields].sort((a, b) => a.name.localeCompare(b.name))
    : scalarFields;

  // Generate scalar-only schema (most common use case)
  const scalarFieldsCode = sortedScalarFields
    .map((field) => {
      const ctx: FieldContext = {
        field,
        modelName: model.name,
        brandedIds,
        config,
      };
      const schemaType = mapFieldToSchema(ctx);
      return `  ${field.name}: ${schemaType}`;
    })
    .join(",\n");

  let code = `export const ${model.name} = Schema.Struct({
${scalarFieldsCode}
})
export type ${model.name} = typeof ${model.name}.Type
`;

  // Optionally generate a schema with relations
  if (config.includeRelations && relationFields.length > 0) {
    const allFields = config.sortFields
      ? [...model.fields].sort((a, b) => a.name.localeCompare(b.name))
      : model.fields;

    const allFieldsCode = allFields
      .map((field) => {
        const ctx: FieldContext = {
          field,
          modelName: model.name,
          brandedIds,
          config,
        };
        const schemaType = mapFieldToSchema(ctx);
        return `  ${field.name}: ${schemaType}`;
      })
      .join(",\n");

    code += `
export const ${model.name}WithRelations = Schema.Struct({
${allFieldsCode}
})
export type ${model.name}WithRelations = typeof ${model.name}WithRelations.Type
`;
  }

  return code;
}

export interface GenerateInput {
  dmmf: DMMF.Document;
  config: ResolvedConfig;
}

export interface GenerateOutput {
  content: string;
  stats: {
    enumCount: number;
    modelCount: number;
    brandedIdCount: number;
  };
}

/**
 * Generates Effect Schema source code from Prisma DMMF
 */
export function generate(input: GenerateInput): GenerateOutput {
  const { dmmf, config } = input;
  const { models, enums } = dmmf.datamodel;

  // Collect branded IDs for all models
  const brandedIds = config.useBrandedIds
    ? collectBrandedIds(models)
    : new Map<string, string>();

  // Build the output
  let output = config.customHeader ?? DEFAULT_HEADER;

  // Add JSON value schema (always needed for Json fields)
  output += JSON_VALUE_SCHEMA;

  // Generate enums (sorted for deterministic output)
  if (enums.length > 0) {
    const sortedEnums = [...enums].sort((a, b) => a.name.localeCompare(b.name));
    output += sectionHeader("Enums");
    output += sortedEnums.map(generateEnumSchema).join("\n");
  }

  // Generate branded IDs
  if (brandedIds.size > 0) {
    output += sectionHeader("Branded IDs");
    output += generateBrandedIdSchemas(brandedIds);
    output += "\n";
  }

  // Generate model schemas (sorted for deterministic output)
  const sortedModels = [...models].sort((a, b) => a.name.localeCompare(b.name));
  output += sectionHeader("Models (scalar fields only)");
  output += sortedModels
    .map((model) => generateModelSchema(model, brandedIds, config))
    .join("\n");

  return {
    content: output,
    stats: {
      enumCount: enums.length,
      modelCount: models.length,
      brandedIdCount: brandedIds.size,
    },
  };
}
