/**
 * Code Templates Module
 *
 * String templates for generating Effect Schema source code.
 * Separated from orchestration logic for clarity and testability.
 */
import type { DMMF } from "@prisma/generator-helper";
import { Array as Arr, HashMap, Order, pipe } from "effect";
import type { GeneratorConfig } from "./config.js";
import type { SchemaResolver } from "./resolver.js";

// ============================================================================
// Constants
// ============================================================================

export const DEFAULT_HEADER = `// This file was auto-generated by prisma-effect-schema
// Do not edit manually - changes will be overwritten
// https://github.com/frontcore/prisma-effect-schema

import { Schema } from "effect"
`;

export const JSON_VALUE_SCHEMA = `// Recursive JSON value schema matching Prisma's JsonValue type
type JsonValue = string | number | boolean | null | JsonArray | JsonObject
type JsonArray = ReadonlyArray<JsonValue>
type JsonObject = { readonly [key: string]: JsonValue }

const JsonValueSchema: Schema.Schema<JsonValue> = Schema.suspend(
  (): Schema.Schema<JsonValue> =>
    Schema.Union(
      Schema.Null,
      Schema.Boolean,
      Schema.Number,
      Schema.String,
      Schema.Array(JsonValueSchema),
      Schema.Record({ key: Schema.String, value: JsonValueSchema })
    )
)
`;

// ============================================================================
// Helpers
// ============================================================================

export const sectionHeader = (title: string): string =>
  `// ============================================================================
// ${title}
// ============================================================================

`;

const ByName = <T extends { name: string }>(): Order.Order<T> =>
  Order.mapInput(Order.string, (item: T) => item.name);

const sortByName = <T extends { name: string }>(items: readonly T[]): T[] =>
  Arr.sort(items, ByName());

// ============================================================================
// Enum Templates
// ============================================================================

export const generateEnumSchema = (enumDef: DMMF.DatamodelEnum): string => {
  const values = pipe(
    sortByName(enumDef.values),
    Arr.map((v) => `"${v.name}"`),
    Arr.join(", ")
  );

  return `export const ${enumDef.name} = Schema.Literal(${values})
export type ${enumDef.name} = typeof ${enumDef.name}.Type`;
};

export const generateEnumSchemas = (
  enums: readonly DMMF.DatamodelEnum[]
): string =>
  pipe(sortByName(enums), Arr.map(generateEnumSchema), Arr.join("\n"));

// ============================================================================
// Branded ID Templates
// ============================================================================

export const generateBrandedIdSchema = ([, brandedIdName]: readonly [
  string,
  string
]): string =>
  `export const ${brandedIdName} = Schema.String.pipe(Schema.brand("${brandedIdName}"))
export type ${brandedIdName} = typeof ${brandedIdName}.Type`;

export const generateBrandedIdSchemas = (
  brandedIds: HashMap.HashMap<string, string>
): string =>
  pipe(
    brandedIds,
    HashMap.toEntries,
    Arr.sort(Order.mapInput(Order.string, ([key]: [string, string]) => key)),
    Arr.map(generateBrandedIdSchema),
    Arr.join("\n\n")
  );

// ============================================================================
// Field Templates
// ============================================================================

export const generateFieldsCode = (
  fields: readonly DMMF.Field[],
  resolver: SchemaResolver,
  sortFields: boolean
): string =>
  pipe(
    sortFields ? sortByName(fields) : fields,
    Arr.map((field) => `  ${field.name}: ${resolver.fieldToSchema(field)}`),
    Arr.join(",\n")
  );

// ============================================================================
// Model Templates
// ============================================================================

export const generateModelSchema = (
  model: DMMF.Model,
  resolver: SchemaResolver,
  config: GeneratorConfig
): string => {
  const scalarFields = model.fields.filter((f) => f.kind !== "object");
  const hasRelations = model.fields.some((f) => f.kind === "object");

  const scalarFieldsCode = generateFieldsCode(
    scalarFields,
    resolver,
    config.sortFields
  );

  const baseSchema = `export const ${model.name} = Schema.Struct({
${scalarFieldsCode}
})
export type ${model.name} = typeof ${model.name}.Type`;

  // Optionally generate schema with relations
  if (!config.includeRelations || !hasRelations) {
    return baseSchema;
  }

  const allFieldsCode = generateFieldsCode(
    model.fields,
    resolver,
    config.sortFields
  );

  return `${baseSchema}

export const ${model.name}WithRelations = Schema.Struct({
${allFieldsCode}
})
export type ${model.name}WithRelations = typeof ${model.name}WithRelations.Type`;
};

export const generateModelSchemas = (
  models: readonly DMMF.Model[],
  makeResolver: (modelName: string) => SchemaResolver,
  config: GeneratorConfig
): string =>
  pipe(
    sortByName(models),
    Arr.map((model) => generateModelSchema(model, makeResolver(model.name), config)),
    Arr.join("\n")
  );
